#!/bin/bash

declare -r kernel_src="/home/$(whoami)/srcs/linux"
declare -r usr_include="/usr/include"
declare -r java_include="/usr/lib/jvm/java-8-openjdk-amd64/include"

declare extra_paths="$usr_include"

usage() {
    echo "otags [-k] [path1..pathN]"
    echo "-k,--kernel - add tags for linux kernel ($kernel_src)"
    echo "-j,--java   - add tags for java includes ($java_include)"
    echo "-c,--clean  - only current directory"
}

while [ "$1" != "" ]; do
    case $1 in
        -k | --kernel ) shift
            extra_paths="$kernel_src"
            ;;
        -j | --java ) shift
            extra_paths="$extra_paths $java_include"
            ;;
        -c | --clean ) shift
            extra_paths=
            ;;
        -h | --help ) usage
            exit 1
            ;;
        -* ) usage
            exit 1
            ;;
        * ) break
    esac
done

echo "Creating file list..."
declare -r files=$(find . $extra_paths \
    \( \
    -name '*.cpp' \
    -or -name '*.c' \
    -or -name '*.h' \
    -or -name '*.hpp' \
    -or -name '*.tpp' \
    -or -name '*.lua' \
    -or -name '*.json' \
    \) \
    -and -type f \
    -and -not -path './nix/output/*' \
    -and -not -path './CMakeFiles/*' \
    -and -not -path '/usr/include/boost/*' \
    -and -not -path '/usr/include/llvm-*/*' \
    -and -not -path '/usr/include/valgrind/*' \
    -and -not -path '/usr/include/python*/*' \
    -and -not -path '/usr/include/x86_64-linux-gnu/c++/5/*' \
    -and -not -path '/usr/include/c++/5/*' \
    -and -not -path './.git/*' \
    -and -not -path './src/mac/*' \
    -and -not -path './src/windows/*' \
    )

echo "Found $(echo $files | wc -w) files"
#for x in $files; do echo $x; done; exit 1

declare -r ctags_cmd="ctags --c++-kinds=+p --fields=+iaS --extra=+q"
rm -f tags
echo "Running $ctags_cmd ..."
$ctags_cmd $files

declare -r cscope_cmd="cscope -bkv"
rm -f cscope.out
echo "Running $cscope_cmd ..."
$cscope_cmd $files

echo "done"
